export const defaultAlbums = [
    "Thriller - Michael Jackson",
    "1989 - Taylor Swift",
    "The Dark Side of the Moon - Pink Floyd",
    "Abbey Road - The Beatles",
    "Good Kid, M.A.A.D City - Kendrick Lamar",
    "My Beautiful Dark Twisted Fantasy - Kanye West",
    "Divide - Ed Sheeran",
    "Future Nostalgia - Dua Lipa",
    "Back to Black - Amy Winehouse",
    "Hotel California - Eagles",
    "Nevermind - Nirvana",
    "The Wall - Pink Floyd",
    "Rumours - Fleetwood Mac",
    "Astroworld - Travis Scott",
    "DAMN. - Kendrick Lamar",
    "Take Care - Drake",
    "Born to Die - Lana Del Rey",
    "Lover - Taylor Swift",
    "A Night at the Opera - Queen",
    "Curtain Call - Eminem",
    "The Marshall Mathers LP - Eminem",
    "American Idiot - Green Day",
    "Legend - Bob Marley & The Wailers",
    "Blonde - Frank Ocean",
    "Channel Orange - Frank Ocean",
    "To Pimp a Butterfly - Kendrick Lamar",
    "Reputation - Taylor Swift",
    "Renaissance - Beyoncé",
    "Lemonade - Beyoncé",
    "Happier Than Ever - Billie Eilish",
    "When We All Fall Asleep, Where Do We Go? - Billie Eilish",
    "Melodrama - Lorde",
    "Pure Heroine - Lorde",
    "Currents - Tame Impala",
    "AM - Arctic Monkeys",
    "Whatever People Say I Am, That's What I'm Not - Arctic Monkeys",
    "Born This Way - Lady Gaga",
    "The Fame Monster - Lady Gaga",
    "Red - Taylor Swift",
    "Justice - Justin Bieber",
    "Purpose - Justin Bieber",
    "Lover - Taylor Swift",
    "Scorpion - Drake",
    "If You're Reading This It's Too Late - Drake",
    "Certified Lover Boy - Drake",
    "Nothing Was The Same - Drake",
    "Views - Drake",
    "Thank U, Next - Ariana Grande",
    "Positions - Ariana Grande",
    "Sweetener - Ariana Grande",
    "The Eminem Show - Eminem",
    "The College Dropout - Kanye West",
    "Late Registration - Kanye West",
    "Graduation - Kanye West",
    "808s & Heartbreak - Kanye West",
    "Yeezus - Kanye West",
    "Watch the Throne - Jay-Z & Kanye West",
    "4:44 - Jay-Z",
    "Blueprint - Jay-Z",
    "Songs in the Key of Life - Stevie Wonder",
    "Purple Rain - Prince",
    "The Chronic - Dr. Dre",
    "Straight Outta Compton - N.W.A.",
    "Ready to Die - The Notorious B.I.G.",
    "Life After Death - The Notorious B.I.G.",
    "All Eyez on Me - 2Pac",
    "Me Against the World - 2Pac",
    "Culture - Migos",
    "Culture II - Migos",
    "Stoney - Post Malone",
    "Beerbongs & Bentleys - Post Malone",
    "Hollywood's Bleeding - Post Malone",
    "After Hours - The Weeknd",
    "Starboy - The Weeknd",
    "Dawn FM - The Weeknd",
    "Beauty Behind the Madness - The Weeknd",
    "House of Balloons - The Weeknd",
    "X - Ed Sheeran",
    "Equals - Ed Sheeran",
    "Multiply - Ed Sheeran",
    "Songs About Jane - Maroon 5",
    "The 20/20 Experience - Justin Timberlake",
    "FutureSex/LoveSounds - Justin Timberlake",
    "Man of the Woods - Justin Timberlake",
    "Bangerz - Miley Cyrus",
    "Plastic Hearts - Miley Cyrus",
    "Endless Summer Vacation - Miley Cyrus",
    "Midnights - Taylor Swift",
    "Speak Now - Taylor Swift",
    "Folklore - Taylor Swift",
    "Evermore - Taylor Swift",
    "Fearless - Taylor Swift",
    "In The Lonely Hour - Sam Smith",
    "Gloria - Sam Smith",
    "How I'm Feeling Now - Charli XCX",
    "Crash - Charli XCX",
    "Anti - Rihanna",
    "Good Girl Gone Bad - Rihanna",
    "Loud - Rihanna",
    "Unapologetic - Rihanna",
    "Talk That Talk - Rihanna",
    "Dangerous Woman - Ariana Grande",
    "Control - SZA",
    "SOS - SZA",
    "Views from the 6 - Drake",
    "More Life - Drake",
    "Nothing But The Beat - David Guetta",
    "One Love - David Guetta",
    "Happier Than Ever - Billie Eilish",
    "Badlands - Halsey",
    "Hopeless Fountain Kingdom - Halsey",
    "Manic - Halsey",
    "If I Can't Have Love, I Want Power - Halsey",
    "Boomerang - JoJo",
    "The High Road - JoJo",
    "Joanne - Lady Gaga",
    "Cheek to Cheek - Lady Gaga & Tony Bennett",
    "Chromatica - Lady Gaga",
    "The Fame - Lady Gaga",
];

export const selectRandomAlbum = () => {
    const randomIndex = Math.floor(Math.random() * defaultAlbums.length);
    return defaultAlbums[randomIndex];
};
