export const defaultArtists = [
    "Drake", 
    "Taylor Swift", 
    "Michael Jackson", 
    "Kanye West", 
    "Kendrick Lamar", 
    "Ed Sheeran", 
    "Dua Lipa", 
    "Elton John",
    "The Weeknd",
    "Ariana Grande",
    "Billie Eilish",
    "Post Malone",
    "Beyoncé",
    "Rihanna",
    "Justin Bieber",
    "Eminem",
    "Bruno Mars",
    "Shawn Mendes",
    "Harry Styles",
    "Adele",
    "Coldplay",
    "Imagine Dragons",
    "Lil Nas X",
    "Doja Cat",
    "SZA",
    "J. Cole",
    "Travis Scott",
    "Lana Del Rey",
    "Frank Ocean",
    "The Rolling Stones",
    "The Beatles",
    "Queen",
    "David Bowie",
    "Prince",
    "Fleetwood Mac",
    "Bob Dylan",
    "Nirvana",
    "Red Hot Chili Peppers",
    "Green Day",
    "Linkin Park",
    "Metallica",
    "AC/DC",
    "Gorillaz",
    "Daft Punk",
    "Calvin Harris",
    "Avicii",
    "Marshmello",
    "Zedd",
    "Diplo",
    "Kygo",
    "Nicki Minaj",
    "Megan Thee Stallion",
    "Cardi B",
    "Lil Wayne",
    "Playboi Carti",
    "21 Savage",
    "Future",
    "Tyler, the Creator",
    "Childish Gambino",
    "Miley Cyrus",
    "Halsey",
    "Sam Smith",
    "The Chainsmokers",
    "One Direction",
    "BLACKPINK",
    "BTS",
    "Stray Kids",
    "TWICE",
    "SEVENTEEN",
    "EXO",
    "IU",
    "Bad Bunny",
    "J Balvin",
    "Maluma",
    "Ozuna",
    "Shakira",
    "Jennifer Lopez",
    "Luis Fonsi",
    "Daddy Yankee",
    "Ricky Martin"
];


export const selectRandomArtist = () => {
    const randomIndex = Math.floor(Math.random() * defaultArtists.length);
    return defaultArtists[randomIndex];
};